import 'package:collection/collection.dart';

/// A class that provides a mapping between flag codes, country codes and
/// language codes.
class FlagCode {
  static const Map<List<String>, String> _flagCodesCountries = {
    ['PSE', 'PS']: 'ps',
    ['AND', 'AD']: 'ad',
    ['ARE', 'AE']: 'ae',
    ['AFG', 'AF']: 'af',
    ['ATG', 'AG']: 'ag',
    ['AIA', 'AI']: 'ai',
    ['ALB', 'AL']: 'al',
    ['ARM', 'AM']: 'am',
    ['AGO', 'AO']: 'ao',
    ['ATA', 'AQ']: 'aq',
    ['ARG', 'AR']: 'ar',
    ['ASM', 'AS']: 'as',
    ['AUT', 'AT']: 'at',
    ['AUS', 'AU']: 'au',
    ['ABW', 'AW']: 'aw',
    ['ALA', 'AX']: 'ax',
    ['AZE', 'AZ']: 'az',
    ['BIH', 'BA']: 'ba',
    ['BRB', 'BB']: 'bb',
    ['BGD', 'BD']: 'bd',
    ['BEL', 'BE']: 'be',
    ['BFA', 'BF']: 'bf',
    ['BGR', 'BG']: 'bg',
    ['BHR', 'BH']: 'bh',
    ['BDI', 'BI']: 'bi',
    ['BEN', 'BJ']: 'bj',
    ['BLM', 'BL']: 'bl',
    ['BMU', 'BM']: 'bm',
    ['BRN', 'BN']: 'bn',
    ['BOL', 'BO']: 'bo',
    ['BRA', 'BR']: 'br',
    ['BHS', 'BS']: 'bs',
    ['BTN', 'BT']: 'bt',
    ['BVT', 'BV']: 'bv',
    ['BWA', 'BW']: 'bw',
    ['BLR', 'BY']: 'by',
    ['BLZ', 'BZ']: 'bz',
    ['CAN', 'CA']: 'ca',
    ['CCK', 'CC']: 'cc',
    ['COD', 'CD']: 'cd',
    ['CAF', 'CF']: 'cf',
    ['COG', 'CG']: 'cg',
    ['CHE', 'CH']: 'ch',
    ['CIV', 'CI']: 'ci',
    ['COK', 'CK']: 'ck',
    ['CHL', 'CL']: 'cl',
    ['CMR', 'CM']: 'cm',
    ['CHN', 'CN']: 'cn',
    ['COL', 'CO']: 'co',
    ['CRI', 'CR']: 'cr',
    ['CUB', 'CU']: 'cu',
    ['CPV', 'CV']: 'cv',
    ['CUW', 'CW']: 'cw',
    ['CXR', 'CX']: 'cx',
    ['CYP', 'CY']: 'cy',
    ['CZE', 'CZ']: 'cz',
    ['DEU', 'DE']: 'de',
    ['DJI', 'DJ']: 'dj',
    ['DNK', 'DK']: 'dk',
    ['DMA', 'DM']: 'dm',
    ['DOM', 'DO']: 'do',
    ['DZA', 'DZ']: 'dz',
    ['ECU', 'EC']: 'ec',
    ['EST', 'EE']: 'ee',
    ['EGY', 'EG']: 'eg',
    ['ESH', 'EH']: 'eh',
    ['ERI', 'ER']: 'er',
    ['ESP', 'ES']: 'es',
    ['ETH', 'ET']: 'et',
    ['FIN', 'FI']: 'fi',
    ['FJI', 'FJ']: 'fj',
    ['FLK', 'FK']: 'fk',
    ['FSM', 'FM']: 'fm',
    ['FRO', 'FO']: 'fo',
    ['FRA', 'FR']: 'fr',
    ['GAB', 'GA']: 'ga',
    ['GBR', 'GB']: 'gb',
    ['GRD', 'GD']: 'gd',
    ['GEO', 'GE']: 'ge',
    ['GUF', 'GF']: 'gf',
    ['GGY', 'GG']: 'gg',
    ['GHA', 'GH']: 'gh',
    ['GIB', 'GI']: 'gi',
    ['GRL', 'GL']: 'gl',
    ['GMB', 'GM']: 'gm',
    ['GIN', 'GN']: 'gn',
    ['GLP', 'GP']: 'gp',
    ['GNQ', 'GQ']: 'gq',
    ['GRC', 'GR']: 'gr',
    ['GTM', 'GT']: 'gt',
    ['GUM', 'GU']: 'gu',
    ['GNB', 'GW']: 'gw',
    ['GUY', 'GY']: 'gy',
    ['HKG', 'HK']: 'hk',
    ['HND', 'HN']: 'hn',
    ['HRV', 'HR']: 'hr',
    ['HTI', 'HT']: 'ht',
    ['HUN', 'HU']: 'hu',
    ['IDN', 'ID']: 'id',
    ['IRL', 'IE']: 'ie',
    ['ISR', 'IL']: 'il',
    ['IND', 'IN']: 'in',
    ['IRQ', 'IQ']: 'iq',
    ['IRN', 'IR']: 'ir',
    ['ISL', 'IS']: 'is',
    ['ITA', 'IT']: 'it',
    ['JPN', 'JP']: 'jp',
    ['KEN', 'KE']: 'ke',
    ['KAZ', 'KZ']: 'kz',
    ['LAO', 'LA']: 'la',
    ['LBN', 'LB']: 'lb',
    ['LIE', 'LI']: 'li',
    ['LTU', 'LT']: 'lt',
    ['LUX', 'LU']: 'lu',
    ['LVA', 'LV']: 'lv',
    ['MYS', 'MY']: 'my',
    ['NPL', 'NP']: 'np',
    ['NLD', 'NL']: 'nl',
    ['NOR', 'NO']: 'no',
    ['OMN', 'OM']: 'om',
    ['PAK', 'PK']: 'pk',
    ['PLW', 'PW']: 'pw',
    ['PRT', 'PT']: 'pt',
    ['QAT', 'QA']: 'qa',
    ['ROU', 'RO']: 'ro',
    ['RUS', 'RU']: 'ru',
    ['SAU', 'SA']: 'sa',
    ['SGP', 'SG']: 'sg',
    ['SWE', 'SE']: 'se',
    ['TUR', 'TR']: 'tr',
    ['UKR', 'UA']: 'ua',
    ['USA', 'US']: 'us',
    ['VNM', 'VN']: 'vn',
    ['ZAF', 'ZA']: 'za',
    ['ZWE', 'ZW']: 'zw',
    ['JAM', 'JM']: 'jm',
    ['JOR', 'JO']: 'jo',
    ['KGZ', 'KG']: 'kg',
    ['KHM', 'KH']: 'kh',
    ['KIR', 'KI']: 'ki',
    ['KNA', 'KN']: 'kn',
    ['KOR', 'KR']: 'kr',
    ['KWT', 'KW']: 'kw',
    ['LBR', 'LR']: 'lr',
    ['LBY', 'LY']: 'ly',
    ['LCA', 'LC']: 'lc',
    ['LKA', 'LK']: 'lk',
    ['LSO', 'LS']: 'ls',
    ['MAC', 'MO']: 'mo',
    ['MAF', 'MF']: 'mf',
    ['MAR', 'MA']: 'ma',
    ['MCO', 'MC']: 'mc',
    ['MDA', 'MD']: 'md',
    ['MDG', 'MG']: 'mg',
    ['MDV', 'MV']: 'mv',
    ['MEX', 'MX']: 'mx',
    ['MHL', 'MH']: 'mh',
    ['MKD', 'MK']: 'mk',
    ['MLI', 'ML']: 'ml',
    ['MLT', 'MT']: 'mt',
    ['MNP', 'MP']: 'mp',
    ['MOZ', 'MZ']: 'mz',
    ['MRT', 'MR']: 'mr',
    ['MSR', 'MS']: 'ms',
    ['MTQ', 'MQ']: 'mq',
    ['MUS', 'MU']: 'mu',
    ['NAM', 'NA']: 'na',
    ['NER', 'NE']: 'ne',
    ['NGA', 'NG']: 'ng',
    ['NIC', 'NI']: 'ni',
    ['NZL', 'NZ']: 'nz',
    ['PAN', 'PA']: 'pa',
    ['PER', 'PE']: 'pe',
    ['PHL', 'PH']: 'ph',
    ['POL', 'PL']: 'pl',
    ['PRK', 'KP']: 'kp',
    ['PRY', 'PY']: 'py',
    ['SGS', 'GS']: 'gs',
    ['IMN', 'IM']: 'im',
    ['IOT', 'IO']: 'io',
    ['JEY', 'JE']: 'je',
    ['COM', 'KM']: 'km',
    ['CYM', 'KY']: 'ky',
    ['MNE', 'ME']: 'me',
    ['MMR', 'MM']: 'mm',
    ['MNG', 'MN']: 'mn',
    ['MWI', 'MW']: 'mw',
    ['NCL', 'NC']: 'nc',
    ['NFK', 'NF']: 'nf',
    ['NRU', 'NR']: 'nr',
    ['NIU', 'NU']: 'nu',
    ['PYF', 'PF']: 'pf',
    ['PNG', 'PG']: 'pg',
    ['SPM', 'PM']: 'pm',
    ['PCN', 'PN']: 'pn',
    ['PRI', 'PR']: 'pr',
    ['REU', 'RE']: 're',
    ['SRB', 'RS']: 'rs',
    ['RWA', 'RW']: 'rw',
    ['SLB', 'SB']: 'sb',
    ['SYC', 'SC']: 'sc',
    ['SDN', 'SD']: 'sd',
    ['SHN', 'SH']: 'sh',
    ['SVN', 'SI']: 'si',
    ['SVK', 'SK']: 'sk',
    ['SLE', 'SL']: 'sl',
    ['SMR', 'SM']: 'sm',
    ['SEN', 'SN']: 'sn',
    ['SOM', 'SO']: 'so',
    ['SUR', 'SR']: 'sr',
    ['SSD', 'SS']: 'ss',
    ['STP', 'ST']: 'st',
    ['SLV', 'SV']: 'sv',
    ['SXM', 'SX']: 'sx',
    ['SYR', 'SY']: 'sy',
    ['SWZ', 'SZ']: 'sz',
    ['TCA', 'TC']: 'tc',
    ['TCD', 'TD']: 'td',
    ['ATF', 'TF']: 'tf',
    ['TGO', 'TG']: 'tg',
    ['THA', 'TH']: 'th',
    ['TJK', 'TJ']: 'tj',
    ['TKL', 'TK']: 'tk',
    ['TLS', 'TL']: 'tl',
    ['TKM', 'TM']: 'tm',
    ['TUN', 'TN']: 'tn',
    ['TON', 'TO']: 'to',
    ['TTO', 'TT']: 'tt',
    ['TUV', 'TV']: 'tv',
    ['TWN', 'TW']: 'tw',
    ['TZA', 'TZ']: 'tz',
    ['UGA', 'UG']: 'ug',
    ['UMI', 'UM']: 'um',
    ['URY', 'UY']: 'uy',
    ['UZB', 'UZ']: 'uz',
    ['VAT', 'VA']: 'va',
    ['VCT', 'VC']: 'vc',
    ['VEN', 'VE']: 've',
    ['VGB', 'VG']: 'vg',
    ['VIR', 'VI']: 'vi',
    ['VUT', 'VU']: 'vu',
    ['WLF', 'WF']: 'wf',
    ['WSM', 'WS']: 'ws',
    ['YEM', 'YE']: 'ye',
    ['MYT', 'YT']: 'yt',
    ['ZMB', 'ZM']: 'zm',
  };

  static const Map<String, String> _flagCodesLanguages = {
    'af': 'af',
    'am': 'et',
    'ar': 'sa',
    'az': 'az',
    'be': 'by',
    'bg': 'bg',
    'bn': 'bd',
    'bs': 'ba',
    'ca': 'ca',
    'cs': 'cz',
    'cy': 'cy',
    'da': 'dk',
    'de': 'de',
    'dv': 'mv',
    'dz': 'bt',
    'el': 'gr',
    'en': 'gb',
    'es': 'es',
    'et': 'ee',
    'eu': 'es',
    'fa': 'ir',
    'fi': 'fi',
    'fo': 'fo',
    'fr': 'fr',
    'gl': 'gl',
    'he': 'il',
    'hi': 'in',
    'hr': 'hr',
    'ht': 'ht',
    'hu': 'hu',
    'hy': 'am',
    'id': 'id',
    'is': 'is',
    'it': 'it',
    'ja': 'jp',
    'ka': 'ge',
    'kk': 'kz',
    'kl': 'gl',
    'km': 'kh',
    'kn': 'in',
    'ko': 'kr',
    'ky': 'kg',
    'la': 'va',
    'lb': 'lu',
    'lo': 'la',
    'lt': 'lt',
    'lv': 'lv',
    'mg': 'mg',
    'mk': 'mk',
    'ml': 'in',
    'mn': 'mn',
    'ms': 'my',
    'mt': 'mt',
    'my': 'mm',
    'na': 'nr',
    'ne': 'np',
    'nl': 'nl',
    'no': 'no',
    'ny': 'mw',
    'pa': 'in',
    'pl': 'pl',
    'pt': 'pt',
    'ro': 'ro',
    'ru': 'ru',
    'rw': 'rw',
    'sm': 'ws',
    'sq': 'al',
    'sr': 'rs',
    'si': 'lk',
    'sk': 'sk',
    'sl': 'si',
    'so': 'so',
    'st': 'za',
    'sv': 'se',
    'sw': 'tz',
    'ta': 'in',
    'te': 'in',
    'th': 'th',
    'ti': 'er',
    'tl': 'ph',
    'to': 'to',
    'tr': 'tr',
    'tk': 'tm',
    'uk': 'ua',
    'ur': 'pk',
    'uz': 'uz',
    'vi': 'vn',
    'zh': 'cn',
    'tg': 'tj',
    'bi': 'vu',
  };

  /// Get the flag code from a language code.
  ///
  /// Returns `null` if the language code is not found.
  ///
  /// Source of the language codes:
  /// http://www.lingoes.net/en/translator/langcode.htm
  static String? fromLanguageCode(String languageCode) =>
      _flagCodesLanguages.entries
          .singleWhereOrNull((entry) => entry.key == languageCode)
          ?.value;

  /// Get the flag code from a country code.
  ///
  /// Returns `null` if the country code is not found.
  static String? fromCountryCode(String countryCode) =>
      _flagCodesCountries.entries
          .singleWhereOrNull((entry) => entry.key.contains(countryCode))
          ?.value;
}
